name: simple_snackbar
description: Simple Snack Bar that you can use throughout your project to display success, error, warning and info messages.
version: 1.0.2
homepage: https://github.com/AJAY-AGARIAN/simple_snackbar

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
